"""empty message

Revision ID: 434dbea17c2
Revises: None
Create Date: 2014-02-12 21:24:05.034875

"""

# revision identifiers, used by Alembic.
revision = '434dbea17c2'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
